### ISSUE TITLE
Seq,truncate returns nulls if given a larger number than the sequence size

### ISSUE THREAD

**Issue by bilkusg** [fsprojects/Fable#118]
### Description

If I have a sequence with, say, 10 elements, and I truncate it to size 20, then according to the F# specs I should just get my sequence back. Instead I get a sequence with 10 elements and 10 nulls, causing havoc in subsequent processing.

I think this is a bug in Seq.truncate on line 13778 of fable-core.js

### Repro steps

Please provide the steps required to reproduce the problem

Include the following code in a browser-hosted page:

       let myList = [1..10]
       let truncatedList = myList |> List.toSeq |> Seq.truncate 20
       let debugStatement = Console.WriteLine (sprintf "%A" myList)
       let debug2Statement = Console.WriteLine (sprintf "%A" (Seq.length truncatedList))

### Expected behavior
Console should show:

     [1,2,3,4,5,6,7,8,9,10]
     [1,2,3,4,5,6,7,8,9,10,null,null,null,null,null,null,null,null,null,null]

### Actual behavior
Console actually shows:

     [1,2,3,4,5,6,7,8,9,10]
     [1,2,3,4,5,6,7,8,9,10,null,null,null,null,null,null,null,null,null,null]

### Known workarounds

Extra check of parameter to ensure no larger than sequence actual size. Only works if sequence is not lazy. Otherwise could write oneself in F# a replacement method.

### Related information 

* Operating system - Windows 10
* Branch - npm beta of fable-compiler as of 9th May 2016
* .NET Runtime, CoreCLR or Mono Version - .Net 4.6

* Performance information, links to performance testing scripts - not relevant

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the detailed report! It seems I didn't get the difference between `take` and `truncate` quite right :/ It should be fixed now. Could you please update the `fable-core` dependency to 0.0.16 and reopen the issue if it's not working? Cheers!

**Comment by bilkusg** [comment]
Many thanks for the impressive turnaround. I will test this tomorrow and reopen if still a problem.
