### ISSUE TITLE
Datetime.ToShortTimeString() not working

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/Fable#321]
I am trying to print a date using: `Datetime.ToShortTimeString()` and it seems to silently crash or stop the code execution.

**Comment by alfonsogarciacaro** [comment]
This is because fable-core is calling internally to `toLocaleTimeString` and it seems not all browsers support this. Maybe we should try to find a workaround. Questions: which browser are you using? And, are you using the core-js polyfill?

**Comment by MangelMaxime** [comment]
Sorry, I forget to give more information..

And in fact it's working on date creating with Fable:

```fsharp
    let test = DateTime.Now;
    console.log (test.ToShortTimeString())
```

I am using Firefox 48.0 and yes I am using core-js polyfill.

My problem is I am calling this function on a string because serialization in DateTime failed. 

So we can close this issue depending on you :).

**Comment by alfonsogarciacaro** [comment]
We can change the subject to allow proper deserialization of dates in `ofJson`. Is the server adding `$type: 'System.DateTime'` as requested by Fable JSON: serialization? https://fsprojects.github.io/Fable/docs/interacting.html#JSON-serialization

**Comment by MangelMaxime** [comment]
No I didn't enabled this options. 
I will try to add it.

**Comment by MangelMaxime** [comment]
I added ` TypeNameHandling.All` but it's doesn't add the `$type` information. Can be caused by the fact I am serializing with a custom converter like:

```csharp
        public override bool CanConvert(Type objectType)
        {
            return (objectType == typeof(ODS_Shared.Rule));
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            throw new NotImplementedException();
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            if (value == null)
            {
                writer.WriteNull();
                return;
            }

            var rule = value as ODS_Shared.Rule;
            writer.WriteStartObject();
            writer.WritePropertyName("Id");
            writer.WriteValue(rule.Id);
            writer.WritePropertyName("Name");
            writer.WriteValue(rule.Name);
            writer.WritePropertyName("ModifiedAt");
            writer.WriteValue(rule.ModifiedAt);
            writer.WritePropertyName("State");
            writer.WriteValue(rule.State.Name);
            writer.WritePropertyName("Services");
            writer.WriteStartArray();
            if (rule.Services != null)
            {
                foreach (var service in rule.Services)
                {
                    serializer.Serialize(writer, service);
                }
            }
            writer.WriteEndArray();
            writer.WritePropertyName("EntryType");
            writer.WriteValue(rule.EntryType);
            writer.WriteEndObject();
        }
```

I will investigate more.

**Comment by MangelMaxime** [comment]
So I wrote a custom converter to handle my self the time, because NewtonSoft don't want to add the types with my convert don't know why.

I have this json:

```json
{
  "success": true,
  "message": "List of the rules",
  "content": [
    {
      "Id": 1,
      "Name": "Doliprane - Lot = 1644, S/N = 12345678901234567890",
      "ModifiedAt": {
        "$type": "System.DateTime",
        "$value": "2016-08-03T17:39:12"
      },
      "State": "Active",
      "Services": [],
      "EntryType": "DATA_MATRIX"
    },
    {
      "Id": 2,
      "Name": "GF Piping Systems",
      "ModifiedAt": {
        "$type": "System.DateTime",
        "$value": "2016-08-03T17:39:12"
      },
      "State": "Active",
      "Services": [
        {
          "Id": 1,
          "Name": "Technical Docs",
          "IconUrl": "http://qr-ut.com/images_app/ICON_locked/NEW/Icone-GF-Apps-Tech-Doc--100pix.png"
        },
        {
          "Id": 2,
          "Name": "Authenticity",
          "IconUrl": ""
        }
      ],
      "EntryType": "QR_CODE"
    },
    {
      "Id": 3,
      "Name": "QR-Codes with any URL",
      "ModifiedAt": {
        "$type": "System.DateTime",
        "$value": "2016-08-03T17:39:12"
      },
      "State": "Active",
      "Services": [],
      "EntryType": "QR_CODE"
    }
  ]
}
```

And still Fable doesn't serialize the DateTime. It's letting it in plain object.

**Comment by MangelMaxime** [comment]
Ok it seems that Fable don't know how to handle the case `System.DateTime`. https://github.com/fsprojects/Fable/blob/master/src/fable/Fable.Core/npm/fable-core.ts#L255

After, if I understand well this [line](https://github.com/fsprojects/Fable/blob/master/src/fable/Fable.Core/npm/fable-core.ts#L290) is a fallback. But in order to deserialize a Datetime we should do `System.Datetime.Parse(value)` and not try to create a new one.

At least it's how I am doing manually for the moment.

**Comment by alfonsogarciacaro** [comment]
This (hopefully) has been fixed in the fable-core 0.5.2 release (please update fable-compiler too just in case). It's been trickier than expected though, because apparently `JSON.stringify` automatically converts `Date` and doesn't let the replacer function change this. There're some positive and negative things about this.

On the plus side:
- We don't need special converters to interact with Json.NET.

On the minus side:
- `DateTime` is always serialized as UTC (maybe this is a plus as, I think, it's a good practice to persist DateTimes in UTC format).
- All strings in DateTime ISO format will be deserialized as `Date` which can conflict if, for some reason, you want to explicitly serialize dates as strings.

Can you please give it a try and close the issue if it works for you now? BTW, now it's possible to do `myDate.ToString("HH:mm")` too :)

**Comment by MangelMaxime** [comment]
Still not working for me.
I will try to give you more code to work with :) just to check if I am doing something wrong.

Here is the json string that I got from the server:

````json
{
  "success": true,
  "message": "List of the rules",
  "content": [
    {
      "Id": 1,
      "Name": "Doliprane - Lot = 1644, S/N = 12345678901234567890",
      "ModifiedAt": {
        "$type": "System.DateTime",
        "$values": "2016-08-03T17:39:12"
      },
      "State": "Inactive",
      "Services": [],
      "EntryType": "DATA_MATRIX"
    }
  ]
}
```

Here are my types using for serializing it:

```fsharp
type ResultJson<'T> = {
  success: bool
  message: string
  content: 'T
}

type Service = {
  Id: int
  Name: string
  IconUrl: string option
}

type Rule = {
  Id: int
  Name: string
  ModifiedAt: DateTime
  State: string
  Services: Service list
  EntryType: string
}

type RuleResult = ResultJson<Rule list>

let result = JsInterop.ofJson<RuleResult> data

result.content |> List.iter(fun x ->
  console.log x
)

// Log: Object { Id: 1, Name: "Doliprane - Lot = 1644, S/N = 12345…", State: "Inactive", Services: Array[0], EntryType: "DATA_MATRIX" }
```

Now I don't even have a trace of ModifiedAt field. Before the new version I was having the field with a string in it.

**Comment by alfonsogarciacaro** [comment]
As commented above, I couldn't make `DateTime` to serialize as `{ $type: ..., $value: ... }`, it has to be serializes as a string in ISO format. This means that when deserializing Fable also [expects `DateTime` to be a string](https://github.com/fsprojects/Fable/blob/master/src/fable/Fable.Core/npm/fable-core.ts#L299).

Can you please try again disabling your custom converter and letting `ModifiedAt` be serialized normally by Json.NET?

**Comment by MangelMaxime** [comment]
Ok I didn't understand it that way sorry :)

I got it working :).

And just for people interested in it, I add to force Json.Net to add the trailing `Z` by telling him to use a TimeZone.

```csharp
return JsonConvert.SerializeObject(
    res, 
    new JsonSerializerSettings
    {
        DateTimeZoneHandling = DateTimeZoneHandling.Utc //Here choose the Zone you want to use.
    }
);
```

Thanks for your help @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
Fantastic! Hmmm, that's weird, Json.NET is adding the `Z` automatically for me (when using `DateTimeKind.Utc`). I'm using Newtonsoft.Json 9.0.1. Fable should be also able to read `DateTime` with a time zone offset, like: `2016-08-04T17:30:00+02:00`

**Comment by MangelMaxime** [comment]
I am taking a date from a Mysql database with Dapper. Perhaps Dapper is not setting all the needed thing.

I will investigate it later.
